services:

  mysql:
    image: mysql:8
    container_name: mysql-expense

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense_db

    ports:
      - "3306:3306"

  expense-tracker:
    image: hardik230900/expense-tracker:v1

    ports:
      - "8080:8080"

    depends_on:
      - mysql

    environment:
      DB_URL: jdbc:mysql://mysql:3306/expense_db
      DB_USERNAME: root
      DB_PASSWORD: root