services:

  mysql:
    image: mysql:8
    container_name: mysql-expense

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense_db

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    ports:
      - "3306:3306"

  expense-tracker:
    image: hardik230900/expense-tracker:v1

    ports:
      - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_URL: jdbc:mysql://mysql:3306/expense_db
      DB_USERNAME: root
      DB_PASSWORD: root